// <auto-generated />
using System;
using InterviewQuestionBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewQuestionBank.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("InterviewQuestionBank.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionRangeStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#5B21B6",
                            Description = "Core C# programming concepts",
                            DisplayOrder = 1,
                            Icon = "fa-code",
                            Name = "C# Fundamentals",
                            QuestionRangeEnd = 50,
                            QuestionRangeStart = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#059669",
                            Description = "ASP.NET MVC and Web Development",
                            DisplayOrder = 2,
                            Icon = "fa-globe",
                            Name = "ASP.NET MVC",
                            QuestionRangeEnd = 90,
                            QuestionRangeStart = 51
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#DC2626",
                            Description = "Advanced .NET & ASP.NET Core",
                            DisplayOrder = 3,
                            Icon = "fa-rocket",
                            Name = "Advanced .NET",
                            QuestionRangeEnd = 99,
                            QuestionRangeStart = 91
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#2563EB",
                            Description = "Azure Cloud Services",
                            DisplayOrder = 4,
                            Icon = "fa-cloud",
                            Name = "Azure Cloud",
                            QuestionRangeEnd = 120,
                            QuestionRangeStart = 100
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#7C3AED",
                            Description = "DevOps, CI/CD and Microservices",
                            DisplayOrder = 5,
                            Icon = "fa-cubes",
                            Name = "DevOps & Microservices",
                            QuestionRangeEnd = 140,
                            QuestionRangeStart = 121
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#EA580C",
                            Description = "Advanced Microservices Patterns",
                            DisplayOrder = 6,
                            Icon = "fa-project-diagram",
                            Name = "Advanced Microservices",
                            QuestionRangeEnd = 171,
                            QuestionRangeStart = 141
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#0891B2",
                            Description = "SQL Server and Database concepts",
                            DisplayOrder = 7,
                            Icon = "fa-database",
                            Name = "SQL Server & Database",
                            QuestionRangeEnd = 200,
                            QuestionRangeStart = 172
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "#0891B2",
                            Description = "Advanced SQL and EF Core",
                            DisplayOrder = 8,
                            Icon = "fa-database",
                            Name = "SQL & Entity Framework",
                            QuestionRangeEnd = 220,
                            QuestionRangeStart = 201
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "#059669",
                            Description = "Modern ASP.NET Core Development",
                            DisplayOrder = 9,
                            Icon = "fa-globe",
                            Name = "ASP.NET Core",
                            QuestionRangeEnd = 240,
                            QuestionRangeStart = 221
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "#F59E0B",
                            Description = "Software Design Patterns",
                            DisplayOrder = 10,
                            Icon = "fa-drafting-compass",
                            Name = "Design Patterns",
                            QuestionRangeEnd = 260,
                            QuestionRangeStart = 241
                        },
                        new
                        {
                            Id = 11,
                            ColorCode = "#10B981",
                            Description = "Testing Strategies and QA",
                            DisplayOrder = 11,
                            Icon = "fa-check-circle",
                            Name = "Testing & Quality",
                            QuestionRangeEnd = 280,
                            QuestionRangeStart = 261
                        },
                        new
                        {
                            Id = 12,
                            ColorCode = "#EF4444",
                            Description = "Application Security",
                            DisplayOrder = 12,
                            Icon = "fa-shield-alt",
                            Name = "Security",
                            QuestionRangeEnd = 300,
                            QuestionRangeStart = 281
                        },
                        new
                        {
                            Id = 13,
                            ColorCode = "#8B5CF6",
                            Description = "Performance and Optimization",
                            DisplayOrder = 13,
                            Icon = "fa-tachometer-alt",
                            Name = "Performance Optimization",
                            QuestionRangeEnd = 320,
                            QuestionRangeStart = 301
                        },
                        new
                        {
                            Id = 14,
                            ColorCode = "#7C3AED",
                            Description = "Microservices Design",
                            DisplayOrder = 14,
                            Icon = "fa-cubes",
                            Name = "Microservices Architecture",
                            QuestionRangeEnd = 340,
                            QuestionRangeStart = 321
                        },
                        new
                        {
                            Id = 15,
                            ColorCode = "#2563EB",
                            Description = "Cloud Technologies and DevOps",
                            DisplayOrder = 15,
                            Icon = "fa-cloud-upload-alt",
                            Name = "Cloud & DevOps",
                            QuestionRangeEnd = 360,
                            QuestionRangeStart = 341
                        },
                        new
                        {
                            Id = 16,
                            ColorCode = "#DC2626",
                            Description = "Advanced .NET Concepts",
                            DisplayOrder = 16,
                            Icon = "fa-rocket",
                            Name = "Advanced .NET Topics",
                            QuestionRangeEnd = 380,
                            QuestionRangeStart = 361
                        },
                        new
                        {
                            Id = 17,
                            ColorCode = "#5B21B6",
                            Description = "Software Architecture",
                            DisplayOrder = 17,
                            Icon = "fa-sitemap",
                            Name = "Architecture & Design",
                            QuestionRangeEnd = 400,
                            QuestionRangeStart = 381
                        },
                        new
                        {
                            Id = 18,
                            ColorCode = "#0891B2",
                            Description = "Database Architecture and Design",
                            DisplayOrder = 18,
                            Icon = "fa-database",
                            Name = "Database Design",
                            QuestionRangeEnd = 420,
                            QuestionRangeStart = 401
                        },
                        new
                        {
                            Id = 19,
                            ColorCode = "#10B981",
                            Description = "Testing Methodologies",
                            DisplayOrder = 19,
                            Icon = "fa-clipboard-check",
                            Name = "Testing & QA Practices",
                            QuestionRangeEnd = 440,
                            QuestionRangeStart = 421
                        },
                        new
                        {
                            Id = 20,
                            ColorCode = "#EA580C",
                            Description = "Large Scale System Design",
                            DisplayOrder = 20,
                            Icon = "fa-project-diagram",
                            Name = "System Design",
                            QuestionRangeEnd = 460,
                            QuestionRangeStart = 441
                        },
                        new
                        {
                            Id = 21,
                            ColorCode = "#DD0031",
                            Description = "Angular Development",
                            DisplayOrder = 21,
                            Icon = "fa-angular",
                            Name = "Angular Framework",
                            QuestionRangeEnd = 376,
                            QuestionRangeStart = 352
                        },
                        new
                        {
                            Id = 24,
                            ColorCode = "#8B5CF6",
                            Description = "Advanced Testing Strategies and Team Leadership",
                            DisplayOrder = 24,
                            Icon = "fa-users-cog",
                            Name = "Advanced Testing & Leadership",
                            QuestionRangeEnd = 480,
                            QuestionRangeStart = 461
                        },
                        new
                        {
                            Id = 25,
                            ColorCode = "#EF4444",
                            Description = "Application Security and OWASP Standards",
                            DisplayOrder = 25,
                            Icon = "fa-lock",
                            Name = "Security & OWASP",
                            QuestionRangeEnd = 500,
                            QuestionRangeStart = 481
                        },
                        new
                        {
                            Id = 26,
                            ColorCode = "#F59E0B",
                            Description = "Technical Leadership and Team Management",
                            DisplayOrder = 26,
                            Icon = "fa-users",
                            Name = "Leadership & Team Management",
                            QuestionRangeEnd = 520,
                            QuestionRangeStart = 501
                        },
                        new
                        {
                            Id = 27,
                            ColorCode = "#7C3AED",
                            Description = "Large-Scale System Design and Scalability",
                            DisplayOrder = 27,
                            Icon = "fa-network-wired",
                            Name = "System Design & Scalability",
                            QuestionRangeEnd = 540,
                            QuestionRangeStart = 521
                        },
                        new
                        {
                            Id = 28,
                            ColorCode = "#10B981",
                            Description = "Core Behavioral Interview Questions",
                            DisplayOrder = 28,
                            Icon = "fa-comments",
                            Name = "Behavioral Questions - Core",
                            QuestionRangeEnd = 560,
                            QuestionRangeStart = 541
                        },
                        new
                        {
                            Id = 29,
                            ColorCode = "#2563EB",
                            Description = "Advanced Behavioral and Situational Questions",
                            DisplayOrder = 29,
                            Icon = "fa-brain",
                            Name = "Behavioral Questions - Advanced",
                            QuestionRangeEnd = 571,
                            QuestionRangeStart = 561
                        });
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.Question", b =>
                {
                    b.HasOne("InterviewQuestionBank.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.UserFavorite", b =>
                {
                    b.HasOne("InterviewQuestionBank.Models.Question", "Question")
                        .WithMany("Favorites")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.UserProgress", b =>
                {
                    b.HasOne("InterviewQuestionBank.Models.Question", "Question")
                        .WithMany("UserProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("InterviewQuestionBank.Models.Question", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
